課題2-4実装
yuta000111/menta.test pull request #5
Opened 2020-12-07 15:20 UTC by yuta000111

2020-12-09 12:30 UTC, myzktkyk requested changes
動作は問題ありませんでした。
1点指摘をしております。

2020-12-09 12:30 UTC, myzktkyk commented on 2-3/app.js
> +    } else { showtodo(); }
以下のようにすれば `showtodo` の `else` 以下の処理が無くせそうな気がします。

```suggestion
    } else { showtodo(todolist); }
```

2020-12-12 03:53 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-12 03:53 UTC, kouki-iwahara commented on 2-3/app.js
> +        return
このreturnは必要でしたか？

2020-12-15 13:50 UTC, merged